version: '3'

services:
  webservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: 'frostbets_tracker_webservice'
    ports:
      - '8080:3000'
    command: 'npm run start:dev'
    depends_on:
      - postgres_db
  postgres_db:
    image: 'postgres:12.6'
    container_name: 'frostbets_tracker_db'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=frostbets_tracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  postgres-data:
